version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    command: --docker --acme.email='${ACME_EMAIL}' --logLevel='${TRAEFIK_LOG_LEVEL}' --acme.dnschallenge.provider='${TRAEFIK_DNS_PROVIDER}' --acme.dnschallenge.delaybeforecheck='${TRAEFIK_DNS_DELAY_BEFORE_CHECK}'
    networks:
      - traefik
    ports:
      - "${TRAEFIK_HOST_HTTP_PORT}:80"
      - "${TRAEFIK_HOST_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./${STAGE}_traefik.toml:/traefik.toml
      - ./.htpasswd:/.htpasswd
      - ./acme:/etc/acme
    env_file:
      - ./.${TRAEFIK_DNS_PROVIDER}-api.key
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:${TRAEFIK_FRONTEND_RULE}'
      - 'traefik.enable=true'


networks:
  traefik:
    driver: bridge

