version: '3.5'

services:
  traefik:
    image: traefik:latest
    restart: always
    networks:
      - traefik
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./traefik_no_https.toml:/traefik.toml
      - ${PRJ_PWD}/.htpasswd:/.htpasswd
      - ./acme:/etc/acme
    env_file:
      - ./.cloudflare-api.key
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:${FRONTEND_RULE_TRK}'
      - 'traefik.enable=true'

networks:
  traefik:
    driver: bridge

