version: '3'

services:
  traefik:
    image: traefik:alpine
    restart: always
    command: --docker --acme.email='${ACME_EMAIL}'
    networks:
      - traefik
    ports:
      - "${TRAEFIK_HOST_HTTP_PORT}:80"
      - "${TRAEFIK_HOST_HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./${STAGE}_traefik.toml:/traefik.toml
      - ./.htpasswd:/.htpasswd
      - ./acme:/etc/acme
    env_file:
      - ./.cloudflare-api.key
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:${FRONTEND_RULE_TRK}'
      - 'traefik.enable=true'


networks:
  traefik:
    driver: bridge

