version: '3'

services:
  traefik:
    #container_name: traefik
    image: traefik:latest
    restart: always
    networks:
      - proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.toml:/traefik.toml
      - ./acme:/etc/acme
    env_file:
      - ./.cloudflare-api.key
  portainer:
      image: portainer/portainer
      command: "--admin-password ${PORTAINER_ADMIN}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer-data:/data
      labels:
        - 'traefik.backend=portainer'
        - 'traefik.port=9000'
        - 'traefik.frontend.rule=Host:portainer.akdev.io'
        - 'traefik.enable=true'
  #      - 'traefik.frontend.auth.basic=secure:$$apr1$$t04RNRaQ$$zR.FacQ1xTk1Ly1cGl7oO.'
      restart: always

networks:
  proxy:
    driver: bridge

